import "./globals.css";
import WagmiProvider from "@/providers/WagmiProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import { Space_Mono } from "next/font/google";
import FloatingCharacters from "@/components/ui/FloatingCharacters";
import ConnectWalletModal from "@/components/modal/ConnectWalletModal";

const spaceMono = Space_Mono({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className} antialiased`}>
        <ReduxProvider>
          <WagmiProvider>
            {" "}
            <ConnectWalletModal />
            <FloatingCharacters />
            {children}
          </WagmiProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
